language: python
os:
  - linux
python:
  - "3.10.5"
jdk:
  - oraclejdk8
script:
  - pip install coverage
  - pip install nose
  - pip install git+git://github.com/timClicks/slate
  - pip install -U pdfminer
  - python -m nltk.downloader punkt
  - python -m nltk.downloader stopwords
  - nosetests --with-coverage --cover-package=tethne
